apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Values.rcName}}
spec:
  replicas: 1
  selector:
    app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{.Values.imageName}}
        ports:
        - containerPort: 8888